# Options for analysis running.
run:
  timeout: 3m

# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  gofumpt:
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - goimports
    - gofumpt

issues:
  exclude-use-default: true
  exclude-dirs:
    - kitex_gen