name: Tests

on: [ push, pull_request ]

jobs:
  unit-benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Unit Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...

  compatibility-test:
    strategy:
      matrix:
        go: [ "1.19", oldstable ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true # don't use cache for self-hosted runners
      - name: Unit Test
        run: go test -race -covermode=atomic ./...